tests/CMakeLists.txt

Changed link ordering

---

eosio.system/abi/eosio.system.abi
eosio.system/include/eosio.system/native.hpp

Correct authority struct in system contract

---

.github/PULL_REQUEST_TEMPLATE.md

Created a template for GitHub pull requests:
/.github/PULL_REQUEST_TEMPLATE.md
Template follows this format. This template will allow AWS lambda functions to pull data from pull requests automagically. Impacts GitHub web interface, no impact on product.
None.
None.
None.

Created Pull Request Template

---

contracts/eosio.bios/include/eosio.bios/eosio.bios.hpp
contracts/eosio.msig/include/eosio.msig/eosio.msig.hpp
contracts/eosio.system/include/eosio.system/eosio.system.hpp
contracts/eosio.system/include/eosio.system/native.hpp
contracts/eosio.token/include/eosio.token/eosio.token.hpp
contracts/eosio.wrap/include/eosio.wrap/eosio.wrap.hpp

Added `eosio::action_wrapper` accessors for all contract's actions.  These will allow for a type-safe and easy way for other contracts to send inline actions to these.

added action_wrappers to headers

---

eosio.system/src/producer_pay.cpp

old unused producer pay constant vars updated and used in reward calculation

old unused producer pay constant vars updated and used in reward calculation

---

contracts/eosio.system/src/producer_pay.cpp

Producer pay vars update

---

contracts/eosio.system/include/eosio.system/rex.results.hpp
contracts/eosio.system/src/rex.cpp
contracts/eosio.system/src/rex.results.cpp
tests/eosio.system_tester.hpp
tests/eosio.system_tests.cpp

Small changes and enhancements to REX smart contract:
1. Used action wrappers for inline transfers.
2. Added dummy inline action, `rentresult`, to `rentcpu` and `rentnet` actions. The action is a no-op. Its data shows the amount of rented tokens.
3. Removed unnecessary `update_rex_account` calls in `deposit`, `rentcpu`, and `rentnet` actions.
4. Added a unit test for `b1` vesting.
5. Added an additional check in `sellrex` action if the actor is the `b1` account. This check makes the action fail if the order cannot be filled immediately. That is, it stops the order from being queued.

REX enhancements - 3 

---

contracts/eosio.system/src/rex.cpp

Fixed a typo in description of runrex action.

fix description comment typo

---

dependencies

Update eosio dependency to release/1.8.x branch.

update eosio dependency to release/1.8.x branch

---

dependencies
pipeline.jsonc

Currently, we have several different configuration files across our repos that control the behavior of various pipelines. This pull request merges all of those configuration files into one, enabling you to define every configurable aspect of behavior on any pipeline running against this repository, for existing and future pipeline features.   
The file is defined in JSON and allows **line** comments, but **no block comments**. The root of the JSON object includes a named object for each pipeline. Every pipeline supports at least two child objects, `pipeline-branch` and `environment`. Support for other child objects, such as `dependencies` or `configuration`, depend on the pipeline.  
The existence of this `pipeline.jsonc` file will cause these standalone config files to be completely …

Created Universal Pipeline Configuration File

---

contracts/eosio.system/include/eosio.system/eosio.system.hpp
contracts/eosio.system/src/eosio.system.cpp
contracts/eosio.system/src/producer_pay.cpp
tests/eosio.system_tester.hpp
tests/eosio.system_tests.cpp

Add configurable inflation to eosio.system contract

---

contracts/eosio.system/README.md

Changing duplicate defcpuloan to defnetloan

Missed defnetloan added

---

contracts/eosio.system/include/eosio.system/exchange_state.hpp
contracts/eosio.system/src/delegate_bandwidth.cpp
contracts/eosio.system/src/eosio.system.cpp
contracts/eosio.system/src/exchange_state.cpp
pipeline.jsonc
tests/eosio.system_tests.cpp

* Fixed producer pay unit tests.
* Improved the estimation in `buyrambytes` action. The action estimates the amount of tokens needed to buy a given number of bytes, then calls `buyram` passing the estimated token amount as an input.

Small Changes to the System Contract

---

contracts/eosio.system/include/eosio.system/exchange_state.hpp
contracts/eosio.system/src/delegate_bandwidth.cpp
contracts/eosio.system/src/exchange_state.cpp
tests/eosio.system_tests.cpp

Improved the estimation in buyrambytes action. The action estimates the amount of tokens needed to buy a given number of bytes, then calls buyram passing the estimated token amount as an input.
Similar to #253.

Improvement to the estimation in buyrambytes action

---

contracts/eosio.token/src/eosio.token.cpp
tests/eosio.msig_tests.cpp
tests/eosio.token_tests.cpp

Added is_account(owner) check to token::open.

Add is_account check to token::open

---

contracts/eosio.system/include/eosio.system/eosio.system.hpp

fix double-move bug in system_contract::registration - v1.6.x

---

contracts/eosio.system/include/eosio.system/eosio.system.hpp

fix double-move bug in system_contract::registration - v1.7.x

---

contracts/eosio.system/include/eosio.system/eosio.system.hpp

fix double-move bug in system_contract::registration - develop

---

CMakeLists.txt
README.md

Bump version to v1.6.1

---

scripts/helper.sh

* Fixed issue in build.sh if the $HOME/eosio directory doesn’t exist.
** Defaults list of subdirectories to empty and performs checks only if $HOME/eosio exists.

Backport PR #298 to r1.7.

---

.cicd/helpers/dependency-info.sh

* Fixed issue where incorrect variable was used when checking if the CDT hash was already specified.
See:
https://buildkite.com/EOSIO/eosio-dot-contracts-beta/builds/572

[1.7.x] CICD fixes

---

README.md
pipeline.jsonc

bump version to v1.9.0-rc1

---

contracts/eosio.system/ricardian/eosio.system.contracts.md.in

Change pronoun in `eosio::buyrex` Ricardian summary.

Change pronoun in buyrex Ricardian summary - v1.8.x

---

contracts/eosio.system/ricardian/eosio.system.contracts.md.in

Change pronoun in `eosio::buyrex` Ricardian summary.

Change pronoun in buyrex Ricardian summary - v1.9.x

---

contracts/eosio.system/ricardian/eosio.system.contracts.md.in

Change pronoun in `eosio::buyrex` Ricardian summary.

Change pronoun in buyrex Ricardian summary - develop

---

.cicd/pipeline.yml

Migration from GKE builders/testers to EKS. This will allow us to scale and maintain these machines much easier.
They're also faster. We see almost half the time for builds in several pipelines (contracts went from 7m to 4m).

[Develop] CI/CD: switch from gke to eks

---

.cicd/pipeline.yml

Migration from GKE builders/testers to EKS. This will allow us to scale and maintain these machines much easier.
They're also faster. We see almost half the time for builds in several pipelines (contracts went from 7m to 4m).

[1.9.x] CI/CD: switch from gke to eks

---

.cicd/pipeline.yml

Migration from GKE builders/testers to EKS. This will allow us to scale and maintain these machines much easier.
They're also faster. We see almost half the time for builds in several pipelines (contracts went from 7m to 4m).

[1.8.x] CI/CD: switch from gke to eks

---

.cicd/pipeline.yml

@jerstern Requested a migration from GKE builders/testers to EKS. This will allow us to scale and maintain these machines much easier.
They're also faster. We see almost half the time for builds in several pipelines (contracts went from 7m to 4m).

[Master] CI/CD: switch from gke to eks

---

contracts/eosio.system/ricardian/eosio.system.contracts.md.in

Change pronoun in `eosio::buyrex` Ricardian summary.

Change pronoun in buyrex Ricardian summary - v1.7.x

---

CMakeLists.txt
README.md

Bump version to v1.7.1

---

CMakeLists.txt
README.md

Bump version to v1.8.1

---

contracts/eosio.system/include/eosio.system/eosio.system.hpp

Move description of eosio.system contract to the appropriate position, above the class definition. This results in better formatted documentation once generated.

Move eosio.system annotations to correct location for more accurate parsing. 

---

CMakeLists.txt
README.md

Bump version to v1.8.2

---

CMakeLists.txt
README.md

Bump version to v1.7.2

---

CMakeLists.txt
README.md
contracts/eosio.system/src/delegate_bandwidth.cpp
contracts/eosio.system/src/name_bidding.cpp
contracts/eosio.system/src/producer_pay.cpp
contracts/eosio.system/src/voting.cpp

Version 1.8.2

---

.cicd/pipeline.yml

Switch to using EKS fleet for 1.7.x builds.
See:
https://buildkite.com/EOSIO/eosio-dot-contracts/builds/866 | Build waiting on non-existing fleet.
https://buildkite.com/EOSIO/eosio-dot-contracts/builds/867 | Build with new fleet.

[1.7.x] Switch to EKS fleet.

---

contracts/eosio.msig/include/eosio.msig/eosio.msig.hpp
contracts/eosio.system/include/eosio.system/exchange_state.hpp
contracts/eosio.system/include/eosio.system/native.hpp
contracts/eosio.system/include/eosio.system/rex.results.hpp
docs/01_key-concepts/01_system.md
docs/01_key-concepts/02_ram.md
docs/01_key-concepts/03_cpu.md
docs/01_key-concepts/04_net.md
docs/01_key-concepts/05_stake.md
docs/01_key-concepts/06_vote.md
docs/03_build-and-deploy.md
docs/04_guides/01_upgrading-the-eosio.system-contract.md
docs/04_guides/05_how-to-create-issue-and-transfer-a-token.md
docs/04_guides/06_how-to-sign-a-multisig-transaction-with-eosio.msig.md
docs/index.md

PR for `docs/split_index_md` that addresses the following issues
- Page title defined in h1 (antipattern)
- Added front-matter fields. 
- Renamed some files, updated some links (no underscores in filenames, use hyphen) 
- Removed doxygen-specific fields from source annotations.

Edits to docs in docs/split_index_md branch

---

CMakeLists.txt
README.md

Bump version to v1.8.3

---

CMakeLists.txt
README.md

Bump version to v1.9.1

---

docs/03_build-and-deploy.md

fix broken link, resolves #470

[Docs] dev - fix broken link

---

README.md

Parallel PR #476 
Resolves #475

Fix link on README.md - 1.9

---

.gitignore
pipeline.jsonc
tests/eosio.msig_tests.cpp
tests/eosio.system_tests.cpp
tests/eosio.wrap_tests.cpp

fixing unit tests error:
```
<skipped>/eosio.contracts/tests/eosio.msig_tests.cpp:298:4: note: candidate function not viable: no known conversion from 'tuple<[...], const std::__1::shared_ptr<const
eosio::chain:😛acked_transaction> &>' to 'tuple<[...], const eosio::chain::signed_transaction &>' for 1st argument
```
https://blockone.atlassian.net/browse/EPE-124

fixing unit tests epe-124

---

contracts/eosio.system/CMakeLists.txt
contracts/eosio.system/src/delegate_bandwidth.cpp

Also relies on https://github.com/EOSIO/eosio.cdt/pull/913

Fix compilation with CDT develop

---

docs/04_guides/01_upgrading-the-eosio.system-contract.md
docs/04_guides/04_how-to-vote.md
docs/04_guides/05_how-to-create-issue-and-transfer-a-token.md
docs/04_guides/06_how-to-sign-a-multisig-transaction-with-eosio.msig.md
docs/04_guides/07_how-to-use-eosio.wrap.md

[docs] Fix shell prompts and codeblocks in commands and results

---

docs/04_guides/01_upgrading-the-eosio.system-contract.md
docs/04_guides/04_how-to-vote.md
docs/04_guides/05_how-to-create-issue-and-transfer-a-token.md
docs/04_guides/06_how-to-sign-a-multisig-transaction-with-eosio.msig.md
docs/04_guides/07_how-to-use-eosio.wrap.md

Backport of PR #521 to `1.9`
Resolves #520

[docs] Fix shell prompts and codeblocks in commands and results - 1.9

---

docs/04_guides/01_upgrading-the-eosio.system-contract.md
docs/04_guides/04_how-to-vote.md
docs/04_guides/05_how-to-create-issue-and-transfer-a-token.md
docs/04_guides/06_how-to-sign-a-multisig-transaction-with-eosio.msig.md
docs/04_guides/07_how-to-use-eosio.wrap.md

Backport of PR #521 to `1.8`
Resolves #520

[docs] Fix shell prompts and codeblocks in commands and results - 1.8

---

contracts/eosio.msig/include/eosio.msig/eosio.msig.hpp
contracts/eosio.msig/src/eosio.msig.cpp

This downgrades the `binary_extension` requirements to that available in `EOSIO.CDT` `v1.6.x` so that abigen can understand it.  In addition, it adds the appropriate annotations to the table structures.

ABI generation fixes for OOB Patch

---

pipeline.jsonc

Because develop of EOSIO.CDT will be out of commission for a bit.  We need to update this temporarily to point to a previous commit.

Temporarily update pipeline.jsonc

---

tests/eosio.rentbw_tests.cpp
tests/main.cpp

Added more output, calculation of fees, and error messages displaying.

add more output and always log errors.

---

contracts/eosio.token/src/eosio.token.cpp

The default error message "unable to find key" while transferring wrong symbol type tokens doesn’t give enough useful information to point someone in the right direction. Changing the error message to "no balance with specified symbol".

Improve error message in token contract

---

tests/eosio.msig_tests.cpp

Add msig approval tests to verify proposal and approvals being sent correctly.  run unit test with debug option as:
"./tests/unit_test   -- --verbose"

Add msig (abi) approval test

---

modeling/simulate.sh
tests/eosio.rentbw_tests.cpp

I put in some changes to process issues with push_action() failures correctly. The code will ignore the input line and move to the next input line. Added support of `--verbose` and sources compilation before execution (not a full recompilation).

Rentbw modeling push action dumps

---

modeling/simulate.sh

Looks like columns were added to `csv_output.csv` file, but column numbers were not adjusted. 
With old values it was plotting `net.exponent` and `net.decay_secs` columns. 
Changed to column numbers corresponding to `cpu.utilization' and `cpu.adjusted_utilization` as shown on the image

Update gnuplot parameters for rentbw modeling

---

docs/04_guides/08_configure-use-powerup-resource-model.md

Update the configuration and install documentation for the Powerup resource model.
- [ X] Documentation Additions

[docs] Update powerup config/install docs

---

CMakeLists.txt
README.md

Bump version to 1.9.2
