- eosio.system/abi/eosio.system.abi
- eosio.system/include/eosio.system/eosio.system.hpp
- eosio.system/src/delegate_bandwidth.cpp
- eosio.system/src/eosio.system.cpp
- eosio.system/src/producer_pay.cpp
Add setramrate method for gradual increase
- this change allows the elected producers to set the ramrate as bytes
per block
- this will also resync the bancor parameters to current eosio.ram
balance plus reduce the volatility of the market maker
- added revision field so that future updates to system contract can
reference it if necessary.
- updated ABI
> Transparent / Gradual Increase to RAM Supply

- eosio.system/src/delegate_bandwidth.cpp
The RAM gift changes assumed the existence of a `get_resource_limits` function in eosiolib (outside of this repo) that took references and apparently was accidentally never committed into the eosio.wasmsdk repo.
PR EOSIO/eosio.wasmsdk#19 properly forward declares the C intrinsic function `get_resource_limits` which takes pointers. This PR makes small changes to properly use the C version of that declared function.
> Use C definition of get_resource_limits which takes pointers

- .gitignore
- eosio.system/include/eosio.system/eosio.system.hpp
- eosio.system/src/delegate_bandwidth.cpp
- eosio.system/src/eosio.system.cpp
- eosio.system/src/producer_pay.cpp
- tests/eosio.system_tests.cpp
Please merge PR #33 first.
This PR makes changes to the way `setramrate` works.
First, it fixes a bug which causes the `setramrate` action to retroactively behave as if the old rate was replaced by the new rate starting from the last time `update_ram_supply()` was called (i.e. going back to `_gstate2.last_ram_increase`). This was because the `_gstate2.new_ram_per_block` was changed prior to `update_ram_supply()` being called in the `setramrate` action handler.
Second, it avoids using the tracked `_gstate.last_block_num` field when it can instead calculate the more accurate `current_block_time()` using the `current_time()` intrinsic function. `current_block_time()` returns the current block's timestamp in `block_timestamp` form (i.e. number of half seconds since 2000). Assuming no slots …
> Fixes and improvements to setramrate

- .gitignore
- CMakeLists.txt
- eosio.bios/CMakeLists.txt
- eosio.bios/abi/eosio.bios.abi
- eosio.bios/include/eosio.bios/eosio.bios.hpp
- eosio.bios/src/eosio.bios.cpp
- eosio.system/abi/eosio.system.abi
- eosio.system/include/eosio.system/eosio.system.hpp
- eosio.system/include/eosio.system/native.hpp
- eosio.system/src/eosio.system.cpp
- tests/contracts.hpp.in
- tests/eosio.system_tests.cpp
The ABI hash table allows wallets to assert that the ABI is what they showed the user or the transaction can be rejected. This pull request merely adds the necessary tracking of ABI, another contract will read the system table and assert.
> Add abi hash

- eosio.system/abi/eosio.system.abi
- eosio.system/include/eosio.system/eosio.system.hpp
- eosio.system/src/delegate_bandwidth.cpp
- eosio.system/src/eosio.system.cpp
- eosio.system/src/producer_pay.cpp
- add setalimits to eosio.system to allow management of resource limits for accounts that were instantiated prior to the resource markets
- migrate inline transfer of bidname refunds to a deferred transaction with a manual failsafe action
Co-authored-by: Bucky Kittinger <larrykittinger@gmail.com>
Co-authored-by: Anton Perkov <anton.perkov@block.one>
> Consolidated Security Fixes for 1.2.1

- eosio.token/abi/eosio.token.abi
- eosio.token/include/eosio.token/eosio.token.hpp
- eosio.token/src/eosio.token.cpp
- tests/eosio.token_tests.cpp
This PR makes two changes:
- It requires authorization of the owner of the zero-balance token row to be closed via `eosio.token::close`.
- It adds the `eosio.token::open` action which resolves #61.
> bug fix in `eosio.token::close` action; add `eosio.token::open` action

- eosio.system/abi/eosio.system.abi
It was added into the bios contract's ABI but missing from the system contract's ABI.
> Add abihash table to system contract ABI

- eosio.token/src/eosio.token.cpp
- tests/eosio.token_tests.cpp
Resolves #93.
Special shoutout to @znebby who actually had a PR (#101) with a proper bug fix out more than half an hour before I started working on this implementation that I unfortunately did not see. Nevertheless we will be merging in this version since it includes unit tests and we want to get a release out soon.
> Ensure symbol actually exists in eosio.token::open

- CMakeLists.txt
- eosio.msig/include/eosio.msig/eosio.msig.hpp
- eosio.msig/src/eosio.msig.cpp
- tests/eosio.msig_tests.cpp
Resolves #87.
This PR modifies the `eosio.msig::approve` action to take an optional `proposal_hash` argument (the new argument is a `binary_extension` which means it can be left off in the serialization without any problems, thus allowing for backwards compatibility of the `eosio.msig::approve` action). 
If and only if the `proposal_hash` is present, the action will assert that the digest provided in `proposal_hash` is identical to the SHA256 hash of the `packed_transaction` in the current referenced proposal (i.e. the ID of the proposed transaction).
Approvers can choose to use this new argument to protect against the proposer of the transaction switching the proposed transaction between the time the approver reviewed it and the time their approval transaction is retired in a block.
> Optionally assert multisig proposed transaction has particular ID as a condition for approval

- eosio.system/include/eosio.system/eosio.system.hpp
- eosio.system/src/delegate_bandwidth.cpp
- eosio.system/src/eosio.system.cpp
- tests/eosio.system_tests.cpp
This PR adds three new actions to the system contract: `setacctram`, `setacctnet`, and `setacctcpu`. These actions allow a specific resource quota of a particular account to be set to a prescribed value regardless of the other changes that happen with that account that would normally affect their resource quotas. All three of these actions require authorization by the `eosio` account, and so are only relevant to the privileged operators of the network, e.g. a two-thirds supermajority of the active block producers if a particular blockchain was configured to unilaterally satisfy the `eosio@active` permission with the `eosio.prods@active` permission. 
For example, `setacctram` can be used to pin the RAM quota of an account to a prescribed value. When the account's RAM quota is pinned in …
> Add functionality to explicitly manage account resources

- eosio.system/src/voting.cpp
Proxy account will no longer be notified when votes proxied to them changes.
> Do not notify proxy when updating votes

- tests/eosio.system_tests.cpp
The tester instance should be configured to not push its bios contract at startup since the unit test is going to push its own bios contract. Previously, if both bios contracts happened to be identical, the test would fail due to a duplicate transaction.
> Fix eosio_system_tests/setabi_bios test

- contracts/eosio.system/CMakeLists.txt
- contracts/eosio.system/include/eosio.system/eosio.system.hpp
- contracts/eosio.system/include/eosio.system/rex.results.hpp
- contracts/eosio.system/src/eosio.system.cpp
- contracts/eosio.system/src/rex.cpp
- contracts/eosio.system/src/rex.results.cpp
- tests/eosio.system_tests.cpp
1. Added a check to ensure that REX loan price is in favor of renting as opposed to staking tokens directly to CPU or Network resources. If the condition is not satisfied, renting actions fail and loans are not renewed.
2. Fixed error in `rex_loans_available()` function. If the queue is non-empty but all the orders have been filled, users can rent CPU and Network resources again.
3. Added ABI support to inline dummy actions. In order for the data of these actions to be deserialized, the ABI of contract `rex.results` which is in file `rex.results.abi` must be deployed on account `eosio.rex`. The actions `buyresult`, `sellresult`, and `orderresult` of `rex.results` are all no-ops. The corresponding contract `rex.results.wasm` must _NOT_ be deployed.
4. Created action `setrex` which allows …
> REX enhancements and bug fixes - 2

- docker/unit-test.sh
Currently, if ctest executes some tests and then exits with a non-zero exit status, the xUnit-formatted XML file it produces will not be uploaded as a Buildkite artifact because those instructions occur after ctest fails the job, stopping execution.     
Now the unit test script disables fail-on-error, runs ctest, saves the ctest exit status, attempts to attach the XML as an artifact, and then re-throws the ctest errors, if one occurred.   
Tested working in eosio.contracts [build 152](https://buildkite.com/EOSIO/eosio-dot-contracts/builds/152#5f956070-2fdd-4709-8b2b-80e253566f56/22-65).  
None.
None.
None.
> Added ctest Error Handling

- contracts/eosio.msig/src/eosio.msig.cpp
This PR works around the `check_transaction_authorization` bug in eosio.cdt v1.6.1 by using the C API directly.
Note for eosio.contracts developers: even when this CDT bug is fixed in v1.6.2, we do not want to return back to the C++ wrapper function because the minimum CDT dependency of contracts would still be 1.6 (the dependency checker does not allow depending on patch releases). The CDT bug only shows up as a warning that most people would ignore. It isn't until the function is actually called during runtime (for example during an `eosio.msig::propose` action) that the bug is encountered (`unreachable executed` errors). 
When eosio.contracts minimum CDT dependency becomes 1.7, we can revert these changes and return back the the wrapped C++ version of `check_transaction_authorization`. …
> workaround check_transaction_authorization bug

- contracts/eosio.system/include/eosio.system/eosio.system.hpp
- contracts/eosio.system/include/eosio.system/native.hpp
- contracts/eosio.system/src/delegate_bandwidth.cpp
- contracts/eosio.system/src/rex.cpp
- contracts/eosio.system/src/voting.cpp
- contracts/eosio.token/include/eosio.token/eosio.token.hpp
- contracts/eosio.token/src/eosio.token.cpp
- tests/eosio.system_tester.hpp
Fix wrong assertion in `create_core_token` (adapted from #189).
Cleanup extraneous and inconsistent license references.
> fix assertion in create_core_token; clean up inconsistent license references - v1.7.x

- build.sh
- docker/buildContracts.sh
- scripts/.environment
- scripts/helper.sh
Adjustments have been made to the eosio.contract build script, build.sh, to support prompt user input for eosio and eosio.cdt installation directories. Flags are now supported and may be passed to the build script to support a non-interactive mode (accepting all default locations and actions) or to supply custom locations at runtime, without input.
Additionally, docker/buildContracts.sh has been updated to use the new flags, supplying non-interactive mode and the expected location of eosio and eosio.cdt.
**NOTE**: This is an implementation of #259 for the release/1.7.x branch.
> Implemented support for custom eosio and eosio.cdt installation paths.

- README.md
- contracts/eosio.system/include/eosio.system/eosio.system.hpp
- contracts/eosio.system/include/eosio.system/native.hpp
- contracts/eosio.system/src/delegate_bandwidth.cpp
- contracts/eosio.system/src/rex.cpp
- contracts/eosio.system/src/voting.cpp
- contracts/eosio.token/include/eosio.token/eosio.token.hpp
- contracts/eosio.token/src/eosio.token.cpp
- tests/CMakeLists.txt
- tests/eosio.system_tester.hpp
Fix wrong assertion in `create_core_token` (adapted from #189).
Cleanup extraneous and inconsistent license references.
Fix links in README.
Set hard max of 1.7 for EOSIO dependency.
> fix assertion in create_core_token; clean up inconsistent license references; fix README links - v1.6.x

- contracts/eosio.bios/include/eosio.bios/eosio.bios.hpp
- contracts/eosio.bios/src/eosio.bios.cpp
- contracts/eosio.msig/src/eosio.msig.cpp
- contracts/eosio.system/include/eosio.system/eosio.system.hpp
- contracts/eosio.system/include/eosio.system/native.hpp
- contracts/eosio.system/src/eosio.system.cpp
- contracts/eosio.token/src/eosio.token.cpp
- contracts/eosio.wrap/src/eosio.wrap.cpp
Add action wrappers for the `activate` and `reqactivated` actions.
Remove unnecessary EOSIO_DISPATCH macros so that the automatic code generation introduced in eosio.cdt v1.6.x can be used instead.
Due to the use of the code generator, `eosio::onerror` notifications will now automatically be rejected by these contracts. That means if any deferred transactions sent by the eosio.system, eosio.msig, or eosio.wrap contracts fail, they would now retire with a status of `hard_fail` rather than `soft_fail` and the CPU and NET usage of that transaction would be billed to the authorizers of the deferred transaction rather than the sending contract.
Furthermore, this PR also disallows directly calling the onerror action in both the eosio.system and eosio.bios contracts. Before this change, it would …
> remove unnecessary EOSIO_DISPATCH macros; add action wrappers for activate and reqactivated actions - develop

- contracts/eosio.bios/include/eosio.bios/eosio.bios.hpp
- contracts/eosio.bios/src/eosio.bios.cpp
- contracts/eosio.msig/src/eosio.msig.cpp
- contracts/eosio.system/include/eosio.system/eosio.system.hpp
- contracts/eosio.system/include/eosio.system/native.hpp
- contracts/eosio.system/src/eosio.system.cpp
- contracts/eosio.token/src/eosio.token.cpp
- contracts/eosio.wrap/src/eosio.wrap.cpp
Add action wrappers for the `activate` and `reqactivated` actions.
Remove unnecessary EOSIO_DISPATCH macros so that the automatic code generation introduced in eosio.cdt v1.6.x can be used instead.
Due to the use of the code generator, `eosio::onerror` notifications will now automatically be rejected by these contracts. That means if any deferred transactions sent by the eosio.system, eosio.msig, or eosio.wrap contracts fail, they would now retire with a status of `hard_fail` rather than `soft_fail` and the CPU and NET usage of that transaction would be billed to the authorizers of the deferred transaction rather than the sending contract.
Furthermore, this PR also disallows directly calling the onerror action in both the eosio.system and eosio.bios contracts. Before this change, it would …
> remove unnecessary EOSIO_DISPATCH macros; add action wrappers for activate and reqactivated actions - v1.7.x

- contracts/eosio.bios/src/eosio.bios.cpp
- contracts/eosio.msig/src/eosio.msig.cpp
- contracts/eosio.system/CMakeLists.txt
- contracts/eosio.system/include/eosio.system/eosio.system.hpp
- contracts/eosio.system/include/eosio.system/exchange_state.hpp
- contracts/eosio.system/include/eosio.system/native.hpp
- contracts/eosio.system/ricardian/eosio.system.contracts.md.in
- contracts/eosio.system/src/delegate_bandwidth.cpp
- contracts/eosio.system/src/eosio.system.cpp
- contracts/eosio.system/src/exchange_state.cpp
- contracts/eosio.system/src/name_bidding.cpp
- contracts/eosio.system/src/native.cpp
- contracts/eosio.system/src/producer_pay.cpp
- contracts/eosio.system/src/rex.cpp
- contracts/eosio.system/src/voting.cpp
- contracts/eosio.token/src/eosio.token.cpp
- contracts/eosio.wrap/src/eosio.wrap.cpp
All usage of raw `_self` is replaced by the `get_self()` accessor function.
The system contract files are rearranged to enable building the system contract by separately compiling individual .cpp files and linking the .o files together into the final .wasm file (similar to the changes done in #267). (There is one exception where the `name_bidding.cpp` file is directly included into the `delegate_bandwidth.cpp` file rather than compiling it separately. This is to work around a problems with the header files in CDT that case duplicate symbol errors when linking. See EOSIO/eosio.cdt#539.) 
Finally, a Ricardian contract is added for the `eosio::setinflation` action.
> separately compile cpp files in system contract; add Ricardian for setinflation action

- contracts/eosio.bios/include/eosio.bios/eosio.bios.hpp
- contracts/eosio.bios/src/eosio.bios.cpp
- contracts/eosio.msig/include/eosio.msig/eosio.msig.hpp
- contracts/eosio.msig/src/eosio.msig.cpp
- contracts/eosio.system/CMakeLists.txt
- contracts/eosio.system/include/eosio.system/eosio.system.hpp
- contracts/eosio.system/include/eosio.system/exchange_state.hpp
- contracts/eosio.system/include/eosio.system/native.hpp
- contracts/eosio.system/include/eosio.system/rex.results.hpp
- contracts/eosio.system/src/delegate_bandwidth.cpp
- contracts/eosio.system/src/eosio.system.cpp
- contracts/eosio.system/src/exchange_state.cpp
- contracts/eosio.system/src/name_bidding.cpp
- contracts/eosio.system/src/native.cpp
- contracts/eosio.system/src/producer_pay.cpp
- contracts/eosio.system/src/rex.cpp
- contracts/eosio.system/src/voting.cpp
- contracts/eosio.token/include/eosio.token/eosio.token.hpp
- contracts/eosio.token/src/eosio.token.cpp
- contracts/eosio.wrap/include/eosio.wrap/eosio.wrap.hpp
- contracts/eosio.wrap/src/eosio.wrap.cpp
Update all contracts to use the new EOSIO.CDT v1.6.x headers rather than the deprecated ones. This part of the PR is effectively a port of #242 for the 1.7.x branch. 
In addition, the upgrade to the new headers requires also bringing in workaround for the check_transaction_authorization bug (see #257 for the version of this workaround that was merged into the develop branch).
Also, all usage of raw `_self` is replaced by the `get_self()` accessor function.
Finally, the system contract files are rearranged to enable building the system contract by separately compiling individual .cpp files and linking the .o files together into the final .wasm file. (There is one exception where the `name_bidding.cpp` file is directly included into the `delegate_bandwidth.cpp` file rather than compiling it …
> update contracts to work with new CDT headers - 1.7

- .cicd/pipeline.yml
- .cicd/travis-build.sh
- .travis.yml
- pipeline.jsonc
This pull request changes the [beta pipelines](https://github.com/EOSIO/eosio.contracts/pull/306) on [Buildkite](https://buildkite.com/EOSIO/eosio-dot-contracts-beta) and [Travis](https://travis-ci.com/EOSIO/eosio.contracts/builds) to pull the base images created on the [eosio-dot-contracts-base-images-beta pipeline](https://buildkite.com/EOSIO/eosio-dot-contracts-base-images-beta) building from the [EOSIO beta pipeline](https://buildkite.com/EOSIO/eosio-beta), instead of previous images build in the (now extinct) [contracts-docker](https://buildkite.com/EOSIO/contracts-docker) pipeline building from GCR.
The `pipeline.jsonc` file had to be updated from `release/1.8.x` to that commit because we can't do base image builds from the release branches until we merge our code into them.
- …
> Build and Test on Images from the eosio-dot-contracts-base-images-beta Pipeline

- contracts/eosio.system/include/eosio.system/eosio.system.hpp
- contracts/eosio.system/ricardian/eosio.system.contracts.md.in
- contracts/eosio.system/src/eosio.system.cpp
- contracts/eosio.system/src/producer_pay.cpp
- tests/eosio.system_tests.cpp
Changed `setinflation` parameters `inflation_pay_factor` and `votepay_factor` as follows:
The fraction of inflation that goes to bp rewards is `10000 / inflation_pay_factor`. For example, if `20%` of inflation going to block producer rewards, `inflation_pay_factor = 50000`.
Per-block pay fraction of bp rewards is `10000 / votepay_factor`. For example:
For `25%` of bp rewards going towards block pay, `votepay_factor = 40000`.
For `75%` of bp rewards going towards block pay, `votepay_factor = 13333`.
> Change setinflation parameters

- .cicd/build.sh
- .cicd/helpers/dependency-info.sh
- .cicd/tests.sh
* Fixed issue where build/test scripts did not have eos installation in PATH.
* Fixed issue where incorrect variable was used when checking if the CDT hash was already specified.
See:
https://buildkite.com/EOSIO/eosio-dot-contracts-beta/builds/571
> [1.6.x] CICD fixes

- contracts/eosio.system/src/producer_pay.cpp
- tests/eosio.system_tests.cpp
Ports #328 to `release/1.8.x`.
> Prevent overflow within claimrewards in cases of extreme inflation - 1.8.x

- contracts/eosio.system/src/producer_pay.cpp
- tests/eosio.system_tests.cpp
Now that it is possible to set the inflation rate using the `setinflation` action, the operators of the network could in theory set the annual inflation rate to an extremely large number. In such a case (and with a large current supply) it is possible for the `new_tokens` amount calculated within `eosio::claimrewards` to overflow into a negative number. Then due to how `to_per_block_pay` and `to_per_block_pay` are calculated using `uint128_t` intermediate variables before being cast to `int64_t`, those two amounts could end up with garbage (possibly negative values). 
The following code demonstrates how such values could be computed in these extreme situations:
```cpp
#include <iostream>
#include <cstdlib>
#include <limits>
#include <cmath>
using uint128_t = unsigned __int128;
int main() …
```
> Prevent overflow within claimrewards in cases of extreme inflation - develop

- .cicd/helpers/dependency-info.sh
Fixed issue where specifying a commit for `eosio` or `eosio.cdt` in `pipeline.jsonc` would result in the build to fail.
- This was due to the checks for `EOSIO_COMMIT` or `CDT_COMMIT` resulting in null strings when checking the GitHub API.
- We took this value and piped into `grep -v 'null'`. This resulted in an exit code of 1 as no strings exist that do not match null.
- This solution now replaces null with empty lines, then removes all empty lines to either get an empty string or the commit HEAD of the branch/tag as determined by GitHub's API. If the string is empty, it means we use the value supplied in `pipeline.jsonc` as originally intended.
See:
[Build #602](https://buildkite.com/EOSIO/eosio-dot-contracts/builds/602) | Buildkite build where the CDT version is specified by a commit …
> [develop] Fix build breaking when specifying commit hash

- .cicd/helpers/dependency-info.sh
Fixed issue where specifying a commit for `eosio` or `eosio.cdt` in `pipeline.jsonc` would result in the build to fail.
- This was due to the checks for `EOSIO_COMMIT` or `CDT_COMMIT` resulting in null strings when checking the GitHub API.
- We took this value and piped into `grep -v 'null'`. This resulted in an exit code of 1 as no strings exist that do not match null.
- This solution now replaces null with empty lines, then removes all empty lines to either get an empty string or the commit HEAD of the branch/tag as determined by GitHub's API. If the string is empty, it means we use the value supplied in `pipeline.jsonc` as originally intended.
> [1.8.x] Fix build breaking when specifying commit hash

- .cicd/helpers/dependency-info.sh
Fixed issue where specifying a commit for `eosio` or `eosio.cdt` in `pipeline.jsonc` would result in the build to fail.
- This was due to the checks for `EOSIO_COMMIT` or `CDT_COMMIT` resulting in null strings when checking the GitHub API.
- We took this value and piped into `grep -v 'null'`. This resulted in an exit code of 1 as no strings exist that do not match null.
- This solution now replaces null with empty lines, then removes all empty lines to either get an empty string or the commit HEAD of the branch/tag as determined by GitHub's API. If the string is empty, it means we use the value supplied in `pipeline.jsonc` as originally intended.
> [1.7.x] Fix build breaking when specifying commit hash

- .cicd/helpers/dependency-info.sh
Fixed issue where specifying a commit for `eosio` or `eosio.cdt` in `pipeline.jsonc` would result in the build to fail.
- This was due to the checks for `EOSIO_COMMIT` or `CDT_COMMIT` resulting in null strings when checking the GitHub API.
- We took this value and piped into `grep -v 'null'`. This resulted in an exit code of 1 as no strings exist that do not match null.
- This solution now replaces null with empty lines, then removes all empty lines to either get an empty string or the commit HEAD of the branch/tag as determined by GitHub's API. If the string is empty, it means we use the value supplied in `pipeline.jsonc` as originally intended.
> [1.6.x] Fix build breaking when specifying commit hash

- CMakeLists.txt
- README.md
- contracts/eosio.bios/include/eosio.bios/eosio.bios.hpp
- contracts/eosio.bios/src/eosio.bios.cpp
- contracts/eosio.msig/src/eosio.msig.cpp
- contracts/eosio.system/include/eosio.system/native.hpp
- contracts/eosio.system/src/native.cpp
- pipeline.jsonc
Updated the minimum CDT dependency to 1.7.x. This means that the eosio.bios and eosio.system contracts can remove their definitions for the preactive_feature and is_feature_activated intrinsics and simply use the ones provided in CDT. It also means that the proper C++ version of `check_transaction_authorization` can be used in eosio.msig rather than the one in the `internal_use_do_not_use` namespace.
> Update minimum CDT dependency to 1.7.x

- README.md
- pipeline.jsonc
- tests/CMakeLists.txt
- tests/eosio.msig_tests.cpp
- tests/eosio.system_tester.hpp
- tests/eosio.system_tests.cpp
- tests/eosio.token_tests.cpp
- tests/eosio.wrap_tests.cpp
Updated the minimum EOSIO dependency to 2.0.x. The tests were updated to work with the latest changes in EOSIO.
> Update minimum EOSIO dependency to 2.0.x

- .cicd/test.sh
- contracts/eosio.bios/include/eosio.bios/eosio.bios.hpp
- contracts/eosio.bios/ricardian/eosio.bios.contracts.md.in
- contracts/eosio.bios/src/eosio.bios.cpp
- contracts/eosio.system/include/eosio.system/eosio.system.hpp
- contracts/eosio.system/ricardian/eosio.system.clauses.md
- contracts/eosio.system/ricardian/eosio.system.contracts.md.in
- contracts/eosio.system/src/voting.cpp
- pipeline.jsonc
- tests/eosio.system_tests.cpp
- tests/main.cpp
Change `setprods` action of the eosio.bios contract to take a vector of `eosio::producer_authority` instead and use the new `set_proposed_producers_ex` intrinsic to propose producer schedules using weighted threshold multisig block signing authorities.
Add the `regproducer2` action to the eosio.system contract to allow block producers candidates to register a weighted threshold multisig block signing authority instead of just a single block signing key. The old `regproducer` action is still usable.
The eosio.system contract and eosio.bios contract can now only be deployed on an EOSIO chain that has activated the [`WTMSIG_BLOCK_SIGNATURES`](https://github.com/EOSIO/eos/pull/7404) protocol feature.
The eosio.bios contract's `setprods` action now takes a vector of `eosio::producer_authority` …
> Allow producers to register  WTMsig block signing authorities in system contract

- .cicd/test.sh
> [develop] Test metrics fix

- .cicd/test.sh
> [1.8.x] Test metrics fix

- .cicd/test.sh
> [1.9.x] Test metrics fix

- .cicd/test.sh
> [1.7.x] Test metrics fix

- .cicd/test.sh
> [1.6.x] Test metrics fix

- contracts/eosio.system/src/name_bidding.cpp
When someone outbids an existing account name, the system contract generates a deferred transaction containing the `eosio::bidrefund` action to return the funds of the account that was outbid. Prior to this PR, this action was authorized by the `active` permission of the `eosio` account which meant the CPU/NET costs of the entire deferred transaction was billed to the `eosio` account. This PR changes the authorizer of the `eosio::bidrefund` action to the `active` permission of the account that was outbid.
> Use authorization of bidder for bidrefund deferred transaction - v1.7.x

- contracts/eosio.system/src/name_bidding.cpp
When someone outbids an existing account name, the system contract generates a deferred transaction containing the `eosio::bidrefund` action to return the funds of the account that was outbid. Prior to this PR, this action was authorized by the `active` permission of the `eosio` account which meant the CPU/NET costs of the entire deferred transaction was billed to the `eosio` account. This PR changes the authorizer of the `eosio::bidrefund` action to the `active` permission of the account that was outbid.
> Use authorization of bidder for bidrefund deferred transaction - v1.8.x

- contracts/eosio.system/src/name_bidding.cpp
When someone outbids an existing account name, the system contract generates a deferred transaction containing the `eosio::bidrefund` action to return the funds of the account that was outbid. Prior to this PR, this action was authorized by the `active` permission of the `eosio` account which meant the CPU/NET costs of the entire deferred transaction was billed to the `eosio` account. This PR changes the authorizer of the `eosio::bidrefund` action to the `active` permission of the account that was outbid.
> Use authorization of bidder for bidrefund deferred transaction - v1.9.x

- contracts/eosio.system/src/name_bidding.cpp
When someone outbids an existing account name, the system contract generates a deferred transaction containing the `eosio::bidrefund` action to return the funds of the account that was outbid. Prior to this PR, this action was authorized by the `active` permission of the `eosio` account which meant the CPU/NET costs of the entire deferred transaction was billed to the `eosio` account. This PR changes the authorizer of the `eosio::bidrefund` action to the `active` permission of the account that was outbid.
> Use authorization of bidder for bidrefund deferred transaction - develop

- contracts/eosio.system/src/delegate_bandwidth.cpp
- contracts/eosio.system/src/producer_pay.cpp
- contracts/eosio.system/src/voting.cpp
Avoid updating `total_activated_stake` after activation. Check for activation using `thresh_activated_stake_time` instead of `total_activated_stake`.
> avoid updating total_activated_stake after activation - v1.8.x

- contracts/eosio.system/src/delegate_bandwidth.cpp
- contracts/eosio.system/src/producer_pay.cpp
- contracts/eosio.system/src/voting.cpp
Avoid updating `total_activated_stake` after activation. Check for activation using `thresh_activated_stake_time` instead of `total_activated_stake`.
> avoid updating total_activated_stake after activation - v1.9.x

- contracts/eosio.system/src/delegate_bandwidth.cpp
- contracts/eosio.system/src/producer_pay.cpp
- contracts/eosio.system/src/voting.cpp
Avoid updating `total_activated_stake` after activation. Check for activation using `thresh_activated_stake_time` instead of `total_activated_stake`.
> avoid updating total_activated_stake after activation - develop

- contracts/eosio.system/src/delegate_bandwidth.cpp
- contracts/eosio.system/src/producer_pay.cpp
- contracts/eosio.system/src/voting.cpp
Avoid updating `total_activated_stake` after activation. Check for activation using `thresh_activated_stake_time` instead of `total_activated_stake`.
> avoid updating total_activated_stake after activation - v1.7.x

- tests/CMakeLists.txt
Fixes verbose warning during compilation.
<hr>
Before:
After:
> Fix CMake warning due to no `project` specified in `tests/CMakeLists.txt`

- contracts/eosio.system/include/eosio.system/eosio.system.hpp
- contracts/eosio.system/src/eosio.system.cpp
- contracts/eosio.system/src/rex.cpp
- tests/eosio.system_tester.hpp
- tests/eosio.system_tests.cpp
The proceeds from CPU and network renting, RAM trading fees, and name bids are currently added immediately to the REX pool, thus instantly increasing the value of REX shares.
We change this pattern and channel the proceeds linearly with time over a period of 30 days. In order to achieve this in a CPU- and RAM-efficient way, we accumulate the proceeds accruing within 12-hour intervals into buckets. At the end of each interval, we start to channel the proceeds in the bucket to the REX pool linearly over 30 days. At the end of the 30 day period, the bucket is deleted. At any point in time, there can be up to a maximum of 60 buckets.
Another change is the `total_unlent` lower bound. It is changed from `20%` to `10%` of `total_lent`.
> Distribute REX returns over time to REX owners

- contracts/eosio.system/include/eosio.system/eosio.system.hpp
- contracts/eosio.system/src/eosio.system.cpp
- contracts/eosio.system/src/rex.cpp
- tests/eosio.system_tester.hpp
- tests/eosio.system_tests.cpp
The proceeds from CPU and network renting, RAM trading fees, and name bids are currently added immediately to the REX pool, thus instantly increasing the value of REX shares.
We change this pattern and channel the proceeds linearly with time over a period of 30 days. In order to achieve this in a CPU- and RAM-efficient way, we accumulate the proceeds accruing within 12-hour intervals into buckets. At the end of each interval, we start to channel the proceeds in the bucket to the REX pool linearly over 30 days. At the end of the 30 day period, the bucket is deleted. At any point in time, there can be up to a maximum of 60 buckets.
Another change is the `total_unlent` lower bound. It is changed from `20%` to `10%` of `total_lent`.
> Distribute REX returns over time to REX owners (release/1.9.x)

- CMakeLists.txt
- README.md
- contracts/eosio.system/include/eosio.system/eosio.system.hpp
- contracts/eosio.system/src/delegate_bandwidth.cpp
- contracts/eosio.system/src/eosio.system.cpp
- contracts/eosio.system/src/producer_pay.cpp
- contracts/eosio.system/src/rentbw.cpp
- contracts/eosio.system/src/rex.cpp
- contracts/eosio.system/src/voting.cpp
- tests/eosio.system_tester.hpp
- tests/eosio.system_tests.cpp
Changes:
* Minor cleanup
* Update to reflect latest changes of v1.8.3.
* Avoid computing exponential in `update_utilization` unnecessarily.
* Ensure `utilization` and `adjusted_utilization` are always less than `weight`:
+ Changes to `update_utilization` to ensure that despite floating pint errors, when decaying the `adjusted_utilization`, `utilization <= new adjusted_utilization <= old adjusted_utilization`, and since `old adjusted_utilization <= weight`, then `new_adjusted_utilization <= weight`.
+ Lower `adjusted_utilization` in `configrentbw` if necessary to ensure that `adjusted_utilization <= weight`.
* Ensure that `utilization_timestamp` always has a meaningful timestamp, including the first time the state singleton is created by `configrentbw`.
* Check that `eosio.reserv` account …
> rentbw changes

- contracts/eosio.system/include/eosio.system/eosio.system.hpp
- contracts/eosio.system/src/rentbw.cpp
- tests/eosio.rentbw_tests.cpp
Changes:
* More cleanup
* Fix name of `configrentbw` action wrapper type.
* Add defaults for `rent_days` (30 days), `decay_secs` (1 day), and `exponent` (2.0).
* Also added defaults for `min_rent_price` and `target_price`. Assuming a core symbol of `symbol("SYS", 4)`, the default for `min_rent_price` would be `0.0100 SYS` and the default for `target_price` would be `100,000,000.0000 SYS`.
* Include calculated rental fee in error message when `max_payment` is too low so that the user has an idea of how much the `max_payment` needs to be under current market conditions.
* Change rounding used in fee calculation to not give an advantage to very small rentals under particular situations (but still under the condition of `utilization >= adjusted_utilization`).
> rentbw additional changes

- contracts/eosio.system/include/eosio.system/eosio.system.hpp
- contracts/eosio.system/src/rentbw.cpp
- tests/eosio.rentbw_tests.cpp
Changes:
* Rename `min_rent_price` to `min_rent_fee` which is a more accurate name.
* Use optionals rather than 0 for config parameters to signal that it should preserve the existing value (or use default when appropriate).
* Modify fee calculation to not give advantage to very small rentals even under the scenario of `utilization <= adjusted_utilization`.
* Add a `min_price` so that the market can be configured to prevent early renters from getting too cheap of a price (defaults to 0).
* Replace `target_price` with the more meaningful `max_price` which also complements `min_price` well. Note: Assuming `min_price` is 0, this modified price model can be directly compared to the prior one. In fact, under that condition, `max_price` can be thought of as `target_price * exponent`.
> rentbw even more changes

- .cicd/build.sh
- .cicd/pipeline.yml
- .cicd/test.sh
PR #338 introduced logic to wait for the dependent Docker image with EOS installed as listed in `pipeline.jsonc` to be built and pushed if it does not exist. [Build #978](https://buildkite.com/EOSIO/eosio-dot-contracts/builds/978#0b3391c8-3115-4f60-9f2a-df1804d60cb1) illustrated a need for the same logic to be applied when downloading the dependent CDT binary:
- Added logic to retry downloading the dependent CDT binary.
- Improved logging output:
- Logs show the command being used to download CDT.
- Logs detail failures when downloading CDT every minute, including a link to the expected build which should have created the artifact.
- Updated build/test commands to support new logic:
- The download is retried until it succeeds. The artifact is now mounted into the build/test container, …
> [1.7.x] Wait for CDT binary.

- .cicd/build.sh
- .cicd/pipeline.yml
- .cicd/test.sh
PR #338 introduced logic to wait for the dependent Docker image with EOS installed as listed in `pipeline.jsonc` to be built and pushed if it does not exist. [Build #978](https://buildkite.com/EOSIO/eosio-dot-contracts/builds/978#0b3391c8-3115-4f60-9f2a-df1804d60cb1) illustrated a need for the same logic to be applied when downloading the dependent CDT binary:
- Added logic to retry downloading the dependent CDT binary.
- Improved logging output:
- Logs show the command being used to download CDT.
- Logs detail failures when downloading CDT every minute, including a link to the expected build which should have created the artifact.
- Updated build/test commands to support new logic:
- The download is retried until it succeeds. The artifact is now mounted into the build/test container, …
> [1.8.x] Wait for CDT binary.

- .cicd/build.sh
- .cicd/pipeline.yml
- .cicd/test.sh
PR #338 introduced logic to wait for the dependent Docker image with EOS installed as listed in `pipeline.jsonc` to be built and pushed if it does not exist. [Build #978](https://buildkite.com/EOSIO/eosio-dot-contracts/builds/978#0b3391c8-3115-4f60-9f2a-df1804d60cb1) illustrated a need for the same logic to be applied when downloading the dependent CDT binary:
- Added logic to retry downloading the dependent CDT binary.
- Improved logging output:
- Logs show the command being used to download CDT.
- Logs detail failures when downloading CDT every minute, including a link to the expected build which should have created the artifact.
- Updated build/test commands to support new logic:
- The download is retried until it succeeds. The artifact is now mounted into the build/test container, …
> [1.9.x] Wait for CDT binary.

- .cicd/build.sh
- .cicd/pipeline.yml
- .cicd/test.sh
- pipeline.jsonc
PR #338 introduced logic to wait for the dependent Docker image with EOS installed as listed in `pipeline.jsonc` to be built and pushed if it does not exist. [Build #978](https://buildkite.com/EOSIO/eosio-dot-contracts/builds/978#0b3391c8-3115-4f60-9f2a-df1804d60cb1) illustrated a need for the same logic to be applied when downloading the dependent CDT binary:
- Added logic to retry downloading the dependent CDT binary.
- Improved logging output:
- Logs show the command being used to download CDT.
- Logs detail failures when downloading CDT every minute, including a link to the expected build which should have created the artifact.
- Updated build/test commands to support new logic:
- The download is retried until it succeeds. The artifact is now mounted into the build/test container, …
> [develop] Wait for CDT binary.

- contracts/eosio.bios/include/eosio.bios/eosio.bios.hpp
- contracts/eosio.msig/include/eosio.msig/eosio.msig.hpp
- contracts/eosio.system/include/eosio.system/eosio.system.hpp
- contracts/eosio.system/include/eosio.system/exchange_state.hpp
- contracts/eosio.system/include/eosio.system/native.hpp
- contracts/eosio.token/include/eosio.token/eosio.token.hpp
- contracts/eosio.wrap/include/eosio.wrap/eosio.wrap.hpp
clean up @details and other arrangements to support the mdjavadoc generator.
reason: @details in annotations are not compatible with mdjavadoc generator.
> docs: clean up @details for release/1.9.x

- .cicd/build.sh
- .cicd/helpers/dependency-info.sh
- .cicd/test.sh
Modified behavior of Contracts builds regarding the specified EOSIO dependency in the `pipeline.jsonc` file:
- Contracts now builds explicitly with the EOSIO dependency listed in `pipeline.jsonc`.
- Buildkite CI no longer uses converted branch/tag names (`$EOSIO_VERSION`) into commit hashes (`$EOSIO_COMMIT`) to pull Docker containers.
- We instead pull Docker containers based on the sanitized (`$EOSIO_VERSION`) input.
- This results in fewer occurrences of wait times for builds when the EOSIO dependency is specified by branch/tag name.
- If the EOSIO dependency is specified by commit hash, CI will still wait if it doesn't already exist.
- No changes made to CDT dependencies at this time.
- Improved environment logging.
- Don't trim commit hashes in log output.
- Log exact Docker command …
> [develop] CI improvements for Deps

- .cicd/build.sh
- .cicd/helpers/dependency-info.sh
- .cicd/test.sh
Modified behavior of Contracts builds regarding the specified EOSIO dependency in the `pipeline.jsonc` file:
- Contracts now builds explicitly with the EOSIO dependency listed in `pipeline.jsonc`.
- Buildkite CI no longer uses converted branch/tag names (`$EOSIO_VERSION`) into commit hashes (`$EOSIO_COMMIT`) to pull Docker containers.
- We instead pull Docker containers based on the sanitized (`$EOSIO_VERSION`) input.
- This results in fewer occurrences of wait times for builds when the EOSIO dependency is specified by branch/tag name.
- If the EOSIO dependency is specified by commit hash, CI will still wait if it doesn't already exist.
- No changes made to CDT dependencies at this time.
- Improved environment logging.
- Don't trim commit hashes in log output.
- Log exact Docker command …
> [1.9.x] CI improvements for Deps

- .cicd/build.sh
- .cicd/helpers/dependency-info.sh
- .cicd/test.sh
Modified behavior of Contracts builds regarding the specified EOSIO dependency in the `pipeline.jsonc` file:
- Contracts now builds explicitly with the EOSIO dependency listed in `pipeline.jsonc`.
- Buildkite CI no longer uses converted branch/tag names (`$EOSIO_VERSION`) into commit hashes (`$EOSIO_COMMIT`) to pull Docker containers.
- We instead pull Docker containers based on the sanitized (`$EOSIO_VERSION`) input.
- This results in fewer occurrences of wait times for builds when the EOSIO dependency is specified by branch/tag name.
- If the EOSIO dependency is specified by commit hash, CI will still wait if it doesn't already exist.
- No changes made to CDT dependencies at this time.
- Improved environment logging.
- Don't trim commit hashes in log output.
- Log exact Docker command …
> [1.8.x] CI improvements for Deps

- contracts/eosio.msig/include/eosio.msig/eosio.msig.hpp
- contracts/eosio.msig/src/eosio.msig.cpp
- contracts/eosio.system/src/delegate_bandwidth.cpp
- contracts/eosio.system/src/name_bidding.cpp
- contracts/eosio.wrap/include/eosio.wrap/eosio.wrap.hpp
- contracts/eosio.wrap/src/eosio.wrap.cpp
- pipeline.jsonc
- tests/eosio.msig_tests.cpp
- tests/eosio.system_tests.cpp
- tests/eosio.wrap_tests.cpp
Deferred transactions are being deprecated. This PR removes any dependency that relies upon deferred transactions in the `eosio.contracts` repository. For further reading, and the rationale behind this PR, please see [Deprecate Deferred Transactions](https://github.com/EOSIO/spec-repo/blob/master/esr_deprecate_deferred.md).
When utilizing the `eosio.multisig` contract a user would perform the action
`propose` and specify (among the proposed transaction and other things) a number
of delay seconds in the transaction header. After proposing the transaction,
users would perform the action `approve` and after, the action `exec`; where if
the approvals of the proposal have been satisfied, the packed transaction (given
in the action `propose`) would get sent out as a deferred transaction that is …
> [develop-deprecate-deferred-trx] Deprecate Deferred Transactions

- .github/workflows/main.yml
This is a quick change to Actions runs when community PRs are submitted:
- Remove now unnecessary job that executed before build/test steps occurred in Github Actions.
- This step was required due to a bug in Actions where if all workflow steps were skipped, such as when org based PRs are executed, the build would be marked as failed.
- The behavior now shows status as expected, where the steps based in the org do now show up at all.
See:
[Actions](https://github.com/EOSIO/eosio.contracts/actions/runs/44374179) | Actions run from #462 showing the same functionality as before.
[Actions](https://github.com/EOSIO/eosio.contracts/actions/runs/44541475) | Actions run created from this PR where all steps are skipped as expected. No checks from Actions show as failed in this PR.
> [1.8.x] Community PR tweaks.

- .github/workflows/main.yml
This is a quick change to Actions runs when community PRs are submitted:
- Remove now unnecessary job that executed before build/test steps occurred in Github Actions.
- This step was required due to a bug in Actions where if all workflow steps were skipped, such as when org based PRs are executed, the build would be marked as failed.
- The behavior now shows status as expected, where the steps based in the org do now show up at all.
See:
[Actions](https://github.com/EOSIO/eosio.contracts/actions/runs/44374179) | Actions run from #462 showing the same functionality as before.
[Actions](https://github.com/EOSIO/eosio.contracts/actions/runs/44540966) | Actions run created from this PR where all steps are skipped as expected. No checks from Actions show as failed in this PR.
> [1.9.x] Community PR tweaks.

- .github/workflows/main.yml
Fixed an issue regarding checkouts when rerunning a failed forked PR:
- Removed use of Actions checkout plugin for several reasons:
- Version 1 of the plugin does not handle the race condition between the "merge commit" being created in Github and trying to checkout this commit.
- Version 2 of the plugin addressed the above issue... but does not allow submodules to be checked out automatically.
- We can use v2 of the plugin and manually checkout submodules... but v2 of the plugin does not checkout the full history of the repo, required for the submodule regression check.
- Actions-based environment variables are set incorrectly on PR reruns of forked repositories...
- Replaced Actions plugin with our own checkout steps:
- Clone the full repo.
- Checkout the specific ref tied to the pull …
> [develop] Actions rerun fixes.

- .github/workflows/main.yml
Fixed an issue regarding checkouts when rerunning a failed forked PR:
- Removed use of Actions checkout plugin for several reasons:
- Version 1 of the plugin does not handle the race condition between the "merge commit" being created in Github and trying to checkout this commit.
- Version 2 of the plugin addressed the above issue... but does not allow submodules to be checked out automatically.
- We can use v2 of the plugin and manually checkout submodules... but v2 of the plugin does not checkout the full history of the repo, required for the submodule regression check.
- Actions-based environment variables are set incorrectly on PR reruns of forked repositories...
- Replaced Actions plugin with our own checkout steps:
- Clone the full repo.
- Checkout the specific ref tied to the pull …
> [1.9.x] Actions rerun fixes.

- .github/workflows/main.yml
Fixed an issue regarding checkouts when rerunning a failed forked PR:
- Removed use of Actions checkout plugin for several reasons:
- Version 1 of the plugin does not handle the race condition between the "merge commit" being created in Github and trying to checkout this commit.
- Version 2 of the plugin addressed the above issue... but does not allow submodules to be checked out automatically.
- We can use v2 of the plugin and manually checkout submodules... but v2 of the plugin does not checkout the full history of the repo, required for the submodule regression check.
- Actions-based environment variables are set incorrectly on PR reruns of forked repositories...
- Replaced Actions plugin with our own checkout steps:
- Clone the full repo.
- Checkout the specific ref tied to the pull …
> [1.8.x] Actions rerun fixes.

- tests/eosio.msig_tests.cpp
- tests/eosio.system_tester.hpp
- tests/eosio.system_tests.cpp
- tests/eosio.token_tests.cpp
- tests/eosio.wrap_tests.cpp
This PR is the develop counterpart of https://github.com/EOSIO/eosio.contracts/pull/501
Background: https://github.com/EOSIO/eos/pull/8823 broke backward compatibility in abi_serializer. It was restored in https://github.com/EOSIO/eos/pull/9128 by reintroducing the affected methods with old signatures as [[deprecated]].
This PR switches from the deprecated old methods that expect an `abi_serializer_max_time` value to the new methods that use a yield function instead.
> use yield function to fix tests to work with EOSIO v2.0.5 and later - develop

- tests/eosio.msig_tests.cpp
- tests/eosio.system_tester.hpp
- tests/eosio.system_tests.cpp
- tests/eosio.token_tests.cpp
- tests/eosio.wrap_tests.cpp
Background: https://github.com/EOSIO/eos/pull/8823 broke backward compatibility in abi_serializer. It was restored in https://github.com/EOSIO/eos/pull/9128 by reintroducing the affected methods with old signatures as [[deprecated]].
This PR switches from the deprecated old methods that expect an `abi_serializer_max_time` value to the new methods that use a yield function instead.
> use yield function to fix tests to work with EOSIO v2.0.5 and later

- contracts/eosio.system/CMakeLists.txt
- contracts/eosio.system/src/delegate_bandwidth.cpp
Backport fix from develop. Without this, 1.9.x can't build with the develop version of CDT.
> Fix compilation with CDT develop

- contracts/eosio.msig/include/eosio.msig/eosio.msig.hpp
- contracts/eosio.msig/src/eosio.msig.cpp
When utilizing the `eosio.multisig` contract a user would perform the action
`propose` and specify (among the proposed transaction and other things) a number
of delay seconds in the transaction header. After proposing the transaction,
users would perform the action `approve` and after, the action `exec`; where if
the approvals of the proposal have been satisfied, the packed transaction (given
in the action `propose`) would get sent out as a deferred transaction that is
delayed by the specified number of delay seconds.
The changes are two-fold:
1) The number of delay seconds is used to calculate the earliest possible
execution time of the action `exec` (of course, once the approvals of the
proposal have been satisfied). The earliest execution time is the point in time
at which the proposal …
> Amend `release/1.8.3-oob`

- contracts/eosio.token/include/eosio.token/eosio.token.hpp
Add additional error messages when using `get_balance` & `get_supply` static methods from `eosio.token`
Error message would change from:
```
Error 3050003: eosio_assert_message assertion failure
Error Details:
assertion failure with message: unable to find key
pending console output: 
```
to =>
```
Error 3050003: eosio_assert_message assertion failure
Error Details:
assertion failure with message: no supply object found
pending console output: 
```
> Add error messages for `get_balance` & `get_supply`

- contracts/eosio.system/CMakeLists.txt
- contracts/eosio.system/include/eosio.system/eosio.system.hpp
- contracts/eosio.system/include/eosio.system/powerup.results.hpp
- contracts/eosio.system/src/powerup.cpp
- contracts/eosio.system/src/powerup.results.cpp
- docs/04_guides/08_configure-use-powerup-resource-model.md
- tests/eosio.powerup_tests.cpp
This is a renaming of `rentbw` to `powerup` per the request of the PBE team. These changes are mostly cosmetic renaming of tables and actions. There is also a commit of a new configuration and usage guide.
- [ X] Deployment Changes
This adds an abi that would need to be deployed to eosio.reserv for a no-op action to notify the account of the NET and CPU weight reserved by the account and the associated fee
- [ X] Documentation Additions
There was the addition of a configuration and usage guide docs/04_guides/08_configure-use-powerup-resource-model.md
> Powerup rename
